### ISSUE TITLE
v2 of the TTF is completely broken

### ISSUE THREAD

**Issue by Xkeeper0** [shannpersand/comic-shanns#9]
Downloaded directly from Github. The font appears like this in Windows 10's preview:
![image](https://user-images.githubusercontent.com/1077535/104821008-aad6c680-57ed-11eb-9f2d-8094d08384ab.png)

This is how it appears in Notepad when typing the following (including four spaces at the start of each line)

    0123456789 ?!
    ABCDEFGHIJKLMNOPQRSTUVWXYZ
    abcdefghijklmnopqrstuvwxyz

![image](https://user-images.githubusercontent.com/1077535/104821034-d659b100-57ed-11eb-9640-9361ba14047f.png)

Edit: This does not affect the OTF version, which works normally.

**Comment by 1234567-glitch** [comment]
@Xkeeper may I help on this issue?

**Comment by andyn** [comment]
Ditto in Fedora 32 and Gnome. Clearly _some_ kind of an off-by-one error, but I don't know the .ttf format enough to debug this any further.

**Comment by shannpersand** [comment]
Bizarre! It appears to be a naming issue after export. No idea what's really going on but seems appending characters to the filename fixes it. 🤷🏻‍♀️  Have uploaded a new file! Give `comic shanns 2.ttf` A try

**Comment by 1234567-glitch** [comment]
Hi to everyone
